---
resources:
- name: myapp-code-repository
  type: git
  source:
    uri: "https://github.com/jskim7827/myapp-code-repository.git"

jobs:
- name: Build App
  plan:
  - get: myapp-code-repository
    trigger: true
  - task: Build App
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.4
      inputs:
        - name: myapp-code-repository
      run:
        path: python
        args:
          - "myapp-code-repository/tests.py"

 - name: run unit tests
  plan:
  - get: myapp-code-repository
    trigger: true
  - task: run unit tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.4
      inputs:
        - name: myapp-code-repository
      run:
        path: python
        args:
          - "myapp-code-repository/tests.py"
