---
resources:
- name: myapp-code-repository1
  type: git
  source:
    uri: "https://github.com/jskim7827/myapp-code-repository1.git"

jobs:
- name: run unit tests
  plan:
  - get: myapp-code-repository1
    trigger: true
  - task: run unit tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.4
      inputs:
        - name: myapp-code-repository1
      run:
        path: python
        args:
          - "myapp-code-repository1/tests.py"

- name: deploy production environment changes
  plan:
  - get: myapp-code-repository1
    trigger: true
    passed:
      - run unit tests
  - task: deploy production environment changes
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.4
      inputs:
        - name: myapp-code-repository1
      run:
